import os
import google.genai as genai
from google.genai import types
from dotenv import load_dotenv
from app.models import SemanticAnalysisResponse

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY not found in environment variables")

client = genai.Client(api_key=GEMINI_API_KEY)

MODEL_ID = "gemini-3-flash-preview"

def analyze_lyrics_semantics(audio_file_path: str, original_lyrics_json: str, target_language: str) -> SemanticAnalysisResponse:
    audio_file = None
    try:
        print("Starting Gemini semantic analysis. Uploading audio file...")
        audio_file = client.files.upload(file=audio_file_path)
        print(f"Audio file uploaded: {audio_file.name}")
        
        # Construct Prompt
        prompt = f"""
        You are an expert musicologist and poetic translator.
        
        We are providing you with the ORIGINAL AUDIO of the song and a DRAFT transcript generated by a speech-to-text model.
        The draft transcript might be empty, incomplete, or full of punctuation if the language is not well supported (e.g., Angolan languages).
        
        Your tasks MUST ALL BE COMPLETED STRICTLY IN THIS TARGET LANGUAGE: **{target_language}**.
        
        1. **Original Lyrics (`lyrics`)**: Listen to the audio and read the draft transcript. If the draft transcript is missing, incomplete, or mostly punctuation (like '.'), IGNORE IT completely. Instead, use the audio to transcribe the lyrics in their ORIGINAL language. Try your best to provide accurate word-level timestamps (`start_time` and `end_time` in M:SS.d format) and line `time`. 
        CRITICAL: If the draft transcript is generally fine and acceptable, DO NOT OUTPUT the `lyrics` array at all. Omit it to save tokens!
        
        2. **Contextual Translation (`translation`)**: Translate the lyrics into {target_language}.
           - CRITICAL: You MUST translate the ENTIRE song from start to finish. Do not stop early or abbreviate!
           - Do NOT perform literal, word-by-word translation. Read the entire song to understand the context, flow, and poetic meaning.
           - Ensure the translated sentences connect logically across the JSON lines, just as they do in a real song.
           - The translated `text` for each line must correspond to the original line's `time`.
           - CRITICAL: Do NOT generate the `words` array for the translation to save output space. Leave the `words` array empty (`[]`) for each translated line.
        
        3. **Semantic Analysis (`meaning` IN {target_language})**:
           - Identify the "vibe", predominant emotions, and the deep meaning of the song.
           - Extract the most important phrases and metaphors and explain them thoroughly.
           - CRITICAL RULE: The `meaning.sentiment`, `meaning.summary`, `meaning.context`, and all `metaphors` explanations MUST be written entirely in {target_language}. Do not write them in English unless the target language is English.

        Provide the output strictly as a JSON object matching the requested schema. Pay meticulous attention to reusing timestamps so they mirror the original JSON / audio perfectly.

        DRAFT ORIGINAL LYRICS:
        {original_lyrics_json}
        """

        # Generate Content with Structured Output
        response = client.models.generate_content(
            model=MODEL_ID,
            contents=[audio_file, prompt],
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=SemanticAnalysisResponse,
                max_output_tokens=8192,
            )
        )
        
        # Parse Response
        if response.parsed:
             return response.parsed
        else:
            return SemanticAnalysisResponse.model_validate_json(response.text)

    except Exception as e:
        print(f"Error in Gemini Service Phase: {e}")
        raise e
    finally:
        if audio_file:
            try:
                print(f"Deleting uploaded audio file from Gemini: {audio_file.name}")
                client.files.delete(name=audio_file.name)
            except Exception as delete_err:
                print(f"Could not delete file {audio_file.name}: {delete_err}")
